import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "./globals.css";

const baiJamJure = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Frozify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(baiJamJure?.className)}>
        <ThemeProvider attribute="class" defaultTheme="white">
          <AntdRegistry>
            <ConfigProvider
              theme={{
                token: {
                  fontFamily: baiJamJure?.style?.fontFamily,
                },
              }}
            >
              {children}
            </ConfigProvider>
          </AntdRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
